// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: ewallet/ewallet.proto

package ewallet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EWalletClient is the client API for EWallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EWalletClient interface {
	CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*CreateWalletReply, error)
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendReply, error)
}

type eWalletClient struct {
	cc grpc.ClientConnInterface
}

func NewEWalletClient(cc grpc.ClientConnInterface) EWalletClient {
	return &eWalletClient{cc}
}

func (c *eWalletClient) CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*CreateWalletReply, error) {
	out := new(CreateWalletReply)
	err := c.cc.Invoke(ctx, "/ewallet.EWallet/CreateWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eWalletClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendReply, error) {
	out := new(SendReply)
	err := c.cc.Invoke(ctx, "/ewallet.EWallet/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EWalletServer is the server API for EWallet service.
// All implementations must embed UnimplementedEWalletServer
// for forward compatibility
type EWalletServer interface {
	CreateWallet(context.Context, *CreateWalletRequest) (*CreateWalletReply, error)
	Send(context.Context, *SendRequest) (*SendReply, error)
	mustEmbedUnimplementedEWalletServer()
}

// UnimplementedEWalletServer must be embedded to have forward compatible implementations.
type UnimplementedEWalletServer struct {
}

func (UnimplementedEWalletServer) CreateWallet(context.Context, *CreateWalletRequest) (*CreateWalletReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWallet not implemented")
}
func (UnimplementedEWalletServer) Send(context.Context, *SendRequest) (*SendReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedEWalletServer) mustEmbedUnimplementedEWalletServer() {}

// UnsafeEWalletServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EWalletServer will
// result in compilation errors.
type UnsafeEWalletServer interface {
	mustEmbedUnimplementedEWalletServer()
}

func RegisterEWalletServer(s grpc.ServiceRegistrar, srv EWalletServer) {
	s.RegisterService(&EWallet_ServiceDesc, srv)
}

func _EWallet_CreateWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EWalletServer).CreateWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ewallet.EWallet/CreateWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EWalletServer).CreateWallet(ctx, req.(*CreateWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EWallet_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EWalletServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ewallet.EWallet/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EWalletServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EWallet_ServiceDesc is the grpc.ServiceDesc for EWallet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EWallet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ewallet.EWallet",
	HandlerType: (*EWalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWallet",
			Handler:    _EWallet_CreateWallet_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _EWallet_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ewallet/ewallet.proto",
}
